# Generated by Django 5.0.6 on 2025-11-04 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SECONDARY_USER', 'Redactor'), ('DIRECTOR', 'Aprobador'), ('AREA_USER', 'Receptor'), ('ADMIN', 'Administrador')], default='SECONDARY_USER', max_length=20),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('prefijo', models.CharField(help_text='Ejemplo: FIN, RH, IT', max_length=10, unique=True, verbose_name='Prefijo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_dirigidos', to=settings.AUTH_USER_MODEL, verbose_name='Director')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='accounts.departamento', verbose_name='Departamento'),
        ),
    ]
