# Generated by Django 5.0.6 on 2025-11-04 02:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_cargo_alter_user_role_departamento_and_more'),
        ('memos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaMemorando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Año')),
                ('ultima_secuencia', models.IntegerField(default=0, verbose_name='Última Secuencia')),
            ],
            options={
                'verbose_name': 'Secuencia de Memorando',
                'verbose_name_plural': 'Secuencias de Memorandos',
                'db_table': 'secuencias_memorandos',
                'ordering': ['-año', 'departamento'],
            },
        ),
        migrations.AddField(
            model_name='memo',
            name='confidencial',
            field=models.BooleanField(default=False, verbose_name='Confidencial'),
        ),
        migrations.AddField(
            model_name='memo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorandos', to='accounts.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='memo',
            name='fecha_distribucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Distribución'),
        ),
        migrations.AddField(
            model_name='memo',
            name='modificacion_solicitada',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios de Modificación'),
        ),
        migrations.AddField(
            model_name='memo',
            name='numero_correlativo',
            field=models.CharField(blank=True, help_text='Formato: [Prefijo]-[Año]-[Secuencial]', max_length=50, null=True, unique=True, verbose_name='Número Correlativo'),
        ),
        migrations.AddField(
            model_name='memo',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='memo',
            name='sello_digital',
            field=models.JSONField(blank=True, help_text='Contiene: director, cargo, departamento, fechaFirma, hash, codigoVerificacion', null=True, verbose_name='Sello Digital'),
        ),
        migrations.AddField(
            model_name='memoattachment',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del Archivo (bytes)'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_APPROVAL', 'Pendiente de Aprobación'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('MODIFICACION_SOLICITADA', 'Modificación Solicitada'), ('DISTRIBUIDO', 'Distribuido')], default='DRAFT', max_length=25, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='memoattachment',
            name='file',
            field=models.FileField(help_text='Formatos permitidos: PDF, DOC, DOCX, XLS, XLSX. Máximo 10MB', upload_to='memo_attachments/', verbose_name='Archivo'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['numero_correlativo'], name='memos_numero__cb1561_idx'),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['status', 'created_at'], name='memos_status_2564e1_idx'),
        ),
        migrations.AddField(
            model_name='secuenciamemorando',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencias', to='accounts.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterUniqueTogether(
            name='secuenciamemorando',
            unique_together={('departamento', 'año')},
        ),
    ]
